//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpotiKat.Configuration {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public int JsonServiceClientMaxNumberOfRetries {
            get {
                return ((int)(this["JsonServiceClientMaxNumberOfRetries"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int JsonServiceSlowDownFactor {
            get {
                return ((int)(this["JsonServiceSlowDownFactor"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<options><option value=\"\"><![CDATA[]]></option><option value=\"0\"><![CDATA[ALL BOO" +
            "MKAT GENRES]]></option><option value=\"basic-channel-slash-dub-techno\"><![CDATA[B" +
            "ASIC CHANNEL / DUB TECHNO]]></option><option value=\"beats-slash-hip-hop\"><![CDAT" +
            "A[BEATS / HIP HOP]]></option><option value=\"dark-ambient-slash-drone-slash-metal" +
            "\"><![CDATA[DARK AMBIENT / DRONE / METAL]]></option><option value=\"disco-slash-bo" +
            "ogie-slash-funk\"><![CDATA[DISCO / BOOGIE / FUNK]]></option><option value=\"dub-sl" +
            "ash-reggae\"><![CDATA[DUB / REGGAE]]></option><option value=\"early-electronic-sla" +
            "sh-soundtracks\"><![CDATA[EARLY ELECTRONIC / SOUNDTRACKS]]></option><option value" +
            "=\"electronic\"><![CDATA[ELECTRONIC]]></option><option value=\"extreme-slash-noise-" +
            "slash-computer-music\"><![CDATA[EXTREME / NOISE / COMPUTER MUSIC]]></option><opti" +
            "on value=\"folk-slash-roots\"><![CDATA[FOLK / ROOTS]]></option><option value=\"grim" +
            "e-slash-fwd\"><![CDATA[GRIME / FWD]]></option><option value=\"indie-slash-alternat" +
            "ive\"><![CDATA[INDIE / ALTERNATIVE]]></option><option value=\"industrial-slash-wav" +
            "e-slash-electro\"><![CDATA[INDUSTRIAL / WAVE / ELECTRO]]></option><option value=\"" +
            "jazz-slash-fusion\"><![CDATA[JAZZ / FUSION]]></option><option value=\"jungle-slash" +
            "-footwork\"><![CDATA[JUNGLE / FOOTWORK]]></option><option value=\"modern-classical" +
            "-slash-ambient\"><![CDATA[MODERN CLASSICAL / AMBIENT]]></option><option value=\"te" +
            "chno-slash-house\"><![CDATA[TECHNO / HOUSE]]></option><option value=\"world\"><![CD" +
            "ATA[WORLD]]></option><option value=\"\"><![CDATA[]]></option><option value=\"sbwr\" " +
            "isLastAlbumRoute=\"true\" source=\"Sbwr\"><![CDATA[SOUNDSBETTERWITHREVERB]]></option" +
            "></options>")]
        public string Genres {
            get {
                return ((string)(this["Genres"]));
            }
        }
    }
}
